[package]
name = "sledtest"
version = "0.1.0"
authors = ["drdr xp <drdr.xp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bench_sled"
path = "src/main.rs"

[[bin]]
name = "ben_sync"
path = "src/ben_sync.rs"

[dependencies]

log = "0.4.14"
env_logger = "0.9.0"
anyhow = "1.0.42"
backtrace = "0.3.60"
futures = "0.3"
rand = "0.8.3"
rayon = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
#sled = { version = "0.34.6", features = ["event_log", "pretty_backtrace"]}
sled = { version = "0.34.6"}
tempfile = "3.2.0"
tokio = { version = "1.8.2", features = ["macros", "rt","rt-multi-thread", "sync"] }
tonic = "0.4.3"
tracing-subscriber = "0.2.18"
tracing="0.1.26"
